import type { WealthData } from "@/types/wealth";

const mockWealthData: WealthData = {
  title: "Net Wealth",
  level1Title: "Wealth overview",
  timestamp: "as of 05 Apr 2023, 12:45PM",

  portfolios: [
    {
      id: "all",
      name: "All portfolios",
      level1Label: "Overview",
      value: 19_575_327,
      currency: "USD",
      changePercentage: 8.9,
    },
    {
      id: "advisory",
      name: "Advisory portfolio",
      value: 8_500_000,
      currency: "USD",
      changePercentage: 18.2,
    },
    {
      id: "execution",
      name: "Execution portfolio",
      value: 6_200_000,
      currency: "USD",
      changePercentage: -5.1,
    },
    {
      id: "retirement",
      name: "Retirement portfolio",
      value: 4_875_327,
      currency: "USD",
      changePercentage: 10.4,
    },
  ],

  details: {
    allPortfolios: {
      netAssetValue: 19_575_327,
      liabilities: 2_150_000,
      ytdPerformance: 8.9,
      availableBorrowing: 4_000_000,
      equitiesAllocation: 60,
      equitiesValue: 11_700_000,
      equitiesHoldings: [
        { security: "NVIDIA (NVDA)", allocation: 9 },
        { security: "Microsoft (MSFT)", allocation: 7 },
        { security: "Apple (AAPL)", allocation: 6 },
        { security: "Amazon (AMZN)", allocation: 5 },
        { security: "Alphabet (GOOGL)", allocation: 4 },
        { security: "Vanguard US Large Cap", allocation: 12 },
        { security: "iShares Core S&P 500", allocation: 10 },
        { security: "Other equities", allocation: 7 },
      ],
      bondsAllocation: 25,
      bondsValue: 4_900_000,
      bondsHoldings: [
        { security: "US Treasury 10Y", allocation: 8 },
        { security: "iShares Core US Agg (AGG)", allocation: 6 },
        { security: "Vanguard Total Bond (BND)", allocation: 5 },
        { security: "Corporate IG ETF", allocation: 3 },
        { security: "TIPS Fund", allocation: 2 },
        { security: "Municipal bonds", allocation: 1 },
      ],
      cashAllocation: 15,
      cashValue: 2_975_327,
      cashHoldings: [
        { security: "USD cash", allocation: 8 },
        { security: "Money market fund", allocation: 4 },
        { security: "Short-term deposits", allocation: 2 },
        { security: "Other liquid assets", allocation: 1 },
      ],
      portfolios: [
        {
          portfolio: "Advisory",
          balance: 8_500_000,
          balanceShare: 43,
          ytdReturn: 18.2,
          allocation: "60/40",
          status: "Outperforming",
          statusVariant: "success",
        },
        {
          portfolio: "Execution",
          balance: 6_200_000,
          balanceShare: 32,
          ytdReturn: -5.1,
          allocation: "70/30",
          status: "Underperforming",
          statusVariant: "warning",
        },
        {
          portfolio: "Retirement",
          balance: 4_875_327,
          balanceShare: 25,
          ytdReturn: 10.4,
          allocation: "50/50",
          status: "On pace",
          statusVariant: "success",
        },
      ],
      rebalancingOpportunities: [
        {
          id: "1",
          observation: "Bond allocation is 2% below target. Consider adding $390K to bonds.",
          impact: "Reduces portfolio volatility by ~0.3%",
        },
        {
          id: "2",
          observation:
            "Your blended portfolio (+8.9% YTD) is outperforming 60/40 benchmark (+6.4%)",
          impact: "Status: On track for long-term goals",
        },
        {
          id: "3",
          observation: "Retirement projection shows $20.5M by retirement (target: $19M)",
          impact: "7% surplus if current savings rate continues",
        },
        {
          id: "4",
          observation: "Cash reserve is above target at 15%. Consider deploying $200K to equities.",
          impact: "May improve long-term growth potential",
        },
        {
          id: "5",
          observation: "Execution portfolio trading costs are 12% below peer average YTD",
          impact: "Estimated savings: $580 this year",
        },
      ],
    },

    advisory: {
      ytdPerformance: 18.2,
      benchmark: 11.8,
      outperformance: 6.4,
      equitiesAllocation: 60,
      equitiesValue: 5_100_000,
      bondsAllocation: 40,
      bondsValue: 3_400_000,
      holdings: [
        { id: "1", security: "Vanguard US Large Cap", allocation: 22, return: 20 },
        { id: "2", security: "iShares Bond ETF", allocation: 18, return: 8.5 },
        { id: "3", security: "Microsoft Corp (MSFT)", allocation: 8, return: 25 },
        { id: "4", security: "Apple Inc (AAPL)", allocation: 6, return: 18 },
        { id: "5", security: "Real Estate ETF (VNQ)", allocation: 5, return: 12 },
      ],
      strategy: "Balanced growth (60/40)",
      fee: 0.75,
      feeEstimateAnnual: 63_750,
      benchmarkTarget: "60% Equities / 40% Bonds",
      rebalancingFrequency: "Quarterly",
      rebalancingDueDays: 45,
      advisorName: "Sarah Johnson",
      alerts: [
        { id: "1", message: "Advisory rebalancing available", actionLabel: "Review" },
        { id: "2", message: "Retirement contribution due this month" },
        { id: "3", message: "On track on your goals" },
      ],
    },

    execution: {
      incoming: 1_945_000,
      outgoing: 2_180_000,
      gains: -316_200,
      ytdReturn: -5.1,
      marketReturn: -7.8,
      outperformance: 2.7,
      tradingCosts: 4960,
      diversificationCount: 28,
      sectorCount: 9,
      countryCount: 12,
      largestPositionName: "Microsoft",
      largestPosition: 8,
      sectorBreakdown: [
        {
          sector: "Technology",
          percentage: 22,
          holdings: [
            { security: "NVIDIA (NVDA)", allocation: 5 },
            { security: "Microsoft (MSFT)", allocation: 4 },
            { security: "Apple (AAPL)", allocation: 3 },
            { security: "Amazon (AMZN)", allocation: 2.5 },
            { security: "Alphabet (GOOGL)", allocation: 2 },
            { security: "Meta (META)", allocation: 2 },
            { security: "Broadcom (AVGO)", allocation: 2 },
            { security: "Other technology", allocation: 1.5 },
          ],
        },
        {
          sector: "Healthcare",
          percentage: 28,
          holdings: [
            { security: "UnitedHealth (UNH)", allocation: 5 },
            { security: "Eli Lilly (LLY)", allocation: 4.5 },
            { security: "Johnson & Johnson (JNJ)", allocation: 4 },
            { security: "Merck (MRK)", allocation: 3.5 },
            { security: "AbbVie (ABBV)", allocation: 3 },
            { security: "Pfizer (PFE)", allocation: 2.5 },
            { security: "Thermo Fisher (TMO)", allocation: 2.5 },
            { security: "Other healthcare", allocation: 3 },
          ],
        },
        {
          sector: "Finance",
          percentage: 15,
          holdings: [
            { security: "JPMorgan Chase (JPM)", allocation: 4 },
            { security: "Berkshire Hathaway (BRK.B)", allocation: 3.5 },
            { security: "Visa (V)", allocation: 2.5 },
            { security: "Mastercard (MA)", allocation: 2.5 },
            { security: "Bank of America (BAC)", allocation: 2.5 },
          ],
        },
        {
          sector: "Industries",
          percentage: 12,
          holdings: [
            { security: "Caterpillar (CAT)", allocation: 4 },
            { security: "Honeywell (HON)", allocation: 3 },
            { security: "Union Pacific (UNP)", allocation: 2.5 },
            { security: "3M (MMM)", allocation: 2.5 },
          ],
        },
        {
          sector: "Consumer",
          percentage: 11,
          holdings: [
            { security: "Procter & Gamble (PG)", allocation: 4 },
            { security: "Coca-Cola (KO)", allocation: 3.5 },
            { security: "Walmart (WMT)", allocation: 3.5 },
          ],
        },
        {
          sector: "Others",
          percentage: 12,
          holdings: [
            { security: "Exxon Mobil (XOM)", allocation: 4 },
            { security: "NextEra Energy (NEE)", allocation: 3 },
            { security: "Real estate (VNQ)", allocation: 2.5 },
            { security: "Other sectors", allocation: 2.5 },
          ],
        },
      ],
      holdings: [
        { id: "1", security: "Vanguard US Large Cap", allocation: 8, return: 32.5 },
        { id: "2", security: "Vanguard US Large Cap", allocation: 8, return: 28.1 },
        { id: "3", security: "Vanguard US Large Cap", allocation: 7, return: 30.2 },
        { id: "4", security: "Vanguard US Large Cap", allocation: 7, return: 27.4 },
        { id: "5", security: "Vanguard US Large Cap", allocation: 6, return: 31.0 },
        { id: "6", security: "Vanguard US Large Cap", allocation: 6, return: 29.8 },
        { id: "7", security: "Vanguard US Large Cap", allocation: 5, return: 26.5 },
        { id: "8", security: "Vanguard US Large Cap", allocation: 5, return: 24.2 },
        { id: "9", security: "Fidelity Intl Growth", allocation: 6, return: 25.0 },
        { id: "10", security: "Schwab S&P 500 Index", allocation: 10, return: 30.0 },
      ],
      activities: [
        { id: "1", type: "buy", message: "Bought : 100 shares NVIDIA @ $450" },
        { id: "2", type: "sell", message: "Sold : 50 shares META @ $310" },
        {
          id: "3",
          type: "info",
          message: "Bought : $5,000 Vanguard Bond ETF rebalancing available",
        },
      ],
      nextSteps: [
        { id: "1", message: "Meta position is down -12.3%" },
        {
          id: "2",
          message: "Your cash position is low at 13%. Consider adding to cash or bonds",
        },
      ],
    },

    retirement: {
      currentBalance: 4_875_327,
      projectedAtRetirement: 20_450_000,
      targetNeeded: 19_000_000,
      projectedSurplus: 1_450_000,
      yearsToRetirement: 22,
      monthlyContribution: 5000,
      annualSavings: 60_000,
      pensions: 12_000,
      totalSavings: 72_000,
      ytdReturn: 10.4,
      expectedAnnualReturn: 6.2,
      currentAllocation: "50% Stocks / 50% Bonds",
      savingsStatusMessage: "You are on track with your YTD contributions",
      accountBreakdown: [
        { type: "401(k)", balance: 2_400_000 },
        { type: "Roth IRA", balance: 1_200_000 },
        { type: "Traditional IRA", balance: 875_000 },
        { type: "Others", balance: 400_327 },
      ],
    },
  },
};

export function useWealthData(): WealthData {
  return mockWealthData;
}
